### ISSUE TITLE
Pronto 0.6.0 support

### ISSUE THREAD

**Issue by mmozuras** [raimondasv/pronto-rails_schema#1]
Hey, 

I've released `0.6.0` of Pronto this week. There's one breaking change you have to be aware of:

`Runner expects to receive patches/commit via initialize(patches, commit), instead of run(patches, commit).`

Here's an example of how to implement that change in the `Runner`:
https://github.com/mmozuras/pronto-scss/commit/c9fa316d422384f82a26872fbde03a62f2892bf3

You can also now pass the `Runner` class as a parameter to `Message.new`. Here's how:
https://github.com/mmozuras/pronto-rubocop/commit/f19d886831e11ad833cb4dc3c9ba3ab41c392246

I think that it's worth implementing both :smile:

**Comment by danigonza** [comment]
pronto-rails_schema supports pronto 0.6.0?
