### ISSUE TITLE
Project status / Pronto 0.11 support

### ISSUE THREAD

**Issue by hlascelles** [raimondasv/pronto-rails_schema#14]
Is this repo still willing to receive PRs, in particular one to support `pronto` 0.11? Thanks!

**Comment by jarl-dk** [comment]
:+1:

**Comment by jarl-dk** [comment]
PR https://github.com/raimondasv/pronto-rails_schema/pull/15 should do the work, just merge :smile:

**Comment by povilasjurcys** [comment]
Solved with https://github.com/raimondasv/pronto-rails_schema/pull/15
